name: Chained-Life
version: '2.0.0'
main: com.ollie.blueprint.ChainedLife
api-version: '1.21'
commands:
  switchpartner:
    description: Switch your chained life partner
    usage: /switchpartner
  setpartners:
    description: Set the partners for Chained-Life
    usage: /setpartners
    permission: chainedlife.setpartners
  endsession:
    description: End a chained life session
    usage: /endsession
    permission: chainedlife.endsession
  lives:
    description: Get or set lives for yourself or other players
    usage: /lives <get|set> [player] [amount]

permissions:
  chainedlife.*:
    description: Gives access to all ChainedLife commands
    default: op
    children:
      chainedlife.switchpartner: true
      chainedlife.setpartners: true
      chainedlife.endsession: true

  chainedlife.switchpartner:
    description: Allows using /switchpartner
    default: op

  chainedlife.setpartners:
    description: Allows using /setpartners
    default: op

  chainedlife.endsession:
    description: Allows use of /endsession
    default: op